import {
  ArticlePost,
  CurrentMatchEvent,
  PerformanceMetrics,
  OptionItem,
  NotificationItem,
} from './JournalistTypes';

export const MOCK_MATCHES: CurrentMatchEvent[] = [
  {
    id: 'match-1',
    competition: 'Egerton Premier League',
    competitionId: 'comp-1',
    homeTeam: 'Tatton FC',
    homeTeamId: 'team-1',
    homeLogo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=100&auto=format&fit=crop&q=80',
    awayTeam: 'Njoro City FC',
    awayTeamId: 'team-2',
    awayLogo: 'https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=100&auto=format&fit=crop&q=80',
    scoreHome: 2,
    scoreAway: 1,
    status: 'LIVE',
    minute: "78'",
    kickoff: '16:00 EAT',
    time: 'Today, 4:00 PM',
    venue: 'Pavilion Main Stadium',
    countdown: '12m remaining',
  },
  {
    id: 'match-2',
    competition: 'Inter-Faculty Cup',
    competitionId: 'comp-2',
    homeTeam: 'Engineering XI',
    homeTeamId: 'team-3',
    homeLogo: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=100&auto=format&fit=crop&q=80',
    awayTeam: 'Agriculture FC',
    awayTeamId: 'team-4',
    awayLogo: 'https://images.unsplash.com/photo-1517649763962-0c623266010b?w=100&auto=format&fit=crop&q=80',
    scoreHome: 0,
    scoreAway: 0,
    status: 'LIVE',
    minute: "34'",
    kickoff: '16:30 EAT',
    time: 'Today, 4:30 PM',
    venue: 'Kilimo Grounds',
    countdown: '11m to HT',
  },
  {
    id: 'match-3',
    competition: 'Egerton Premier League',
    competitionId: 'comp-1',
    homeTeam: 'Maragoli Strikers',
    homeTeamId: 'team-5',
    awayTeam: 'Medical Stars',
    awayTeamId: 'team-6',
    scoreHome: 0,
    scoreAway: 0,
    status: 'UPCOMING',
    kickoff: '18:00 EAT',
    time: 'Today, 6:00 PM',
    venue: 'Pavilion Turf B',
    countdown: 'Starts in 1h 45m',
  },
  {
    id: 'match-4',
    competition: 'Campus Championship',
    competitionId: 'comp-3',
    homeTeam: 'Computer Science FC',
    homeTeamId: 'team-7',
    awayTeam: 'Environmental Warriors',
    awayTeamId: 'team-8',
    scoreHome: 0,
    scoreAway: 0,
    status: 'UPCOMING',
    kickoff: 'Tomorrow, 15:00',
    time: 'Tomorrow, 3:00 PM',
    venue: 'Njoro Grounds',
    countdown: 'Tomorrow',
  },
  {
    id: 'match-5',
    competition: 'Egerton Premier League',
    competitionId: 'comp-1',
    homeTeam: 'Veterinary Lions',
    homeTeamId: 'team-9',
    awayTeam: 'Education Heroes',
    awayTeamId: 'team-10',
    scoreHome: 3,
    scoreAway: 1,
    status: 'FT',
    kickoff: 'Yesterday',
    time: 'Yesterday, 4:00 PM',
    venue: 'Pavilion Main Stadium',
  },
];

export const MOCK_COMPETITIONS: OptionItem[] = [
  { id: 'comp-1', name: 'Egerton Premier League' },
  { id: 'comp-2', name: 'Inter-Faculty Cup' },
  { id: 'comp-3', name: 'Campus Championship' },
  { id: 'comp-4', name: 'East Africa Varsity Games' },
];

export const MOCK_TEAMS: OptionItem[] = [
  { id: 'team-1', name: 'Tatton FC' },
  { id: 'team-2', name: 'Njoro City FC' },
  { id: 'team-3', name: 'Engineering XI' },
  { id: 'team-4', name: 'Agriculture FC' },
  { id: 'team-5', name: 'Maragoli Strikers' },
  { id: 'team-6', name: 'Medical Stars' },
  { id: 'team-7', name: 'Computer Science FC' },
  { id: 'team-8', name: 'Environmental Warriors' },
];

export const INITIAL_ARTICLES: ArticlePost[] = [
  {
    id: 'art-1',
    headline: 'BREAKING: Tatton FC Edge Njoro City 2-1 in Thrilling Derby Finish!',
    subtitle: 'An 88th-minute header by Captain Ombati seals top spot in Egerton Premier League.',
    body: 'In a packed Pavilion Stadium, Tatton FC snatched victory from the jaws of a draw against rivals Njoro City FC. With the match tied at 1-1 entering final minutes, Ombati rose highest to head home from a pinpoint corner kick, putting Tatton 3 points clear at the summit.',
    category: 'breaking_news',
    timestamp: '25m ago',
    publishedAt: new Date().toISOString(),
    isToday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    images: ['https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80'],
    status: 'published',
    viewsCount: 1420,
    matchId: 'match-1',
    matchTitle: 'Tatton FC vs Njoro City FC',
    teamId: 'team-1',
    teamName: 'Tatton FC',
    competitionId: 'comp-1',
    competitionName: 'Egerton Premier League',
    interactions: {
      likesCount: 245,
      repostsCount: 54,
      commentsCount: 19,
      viewsCount: 1420,
      bookmarksCount: 38,
    },
  },
  {
    id: 'art-2',
    headline: 'MATCH REPORT: Engineering XI and Agriculture FC Battle Out Goalless First Half',
    subtitle: 'Tactical stalemate in Inter-Faculty Cup opening group clash.',
    body: 'Both sides displayed rigorous defensive formations in the first half at Kilimo Grounds. Engineering XI registered 4 shots on target but failed to beat Agriculture keeper Otieno.',
    category: 'match_report',
    timestamp: '1h ago',
    publishedAt: new Date().toISOString(),
    isToday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    images: ['https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&auto=format&fit=crop&q=80'],
    status: 'published',
    viewsCount: 890,
    matchId: 'match-2',
    matchTitle: 'Engineering XI vs Agriculture FC',
    teamId: 'team-3',
    teamName: 'Engineering XI',
    competitionId: 'comp-2',
    competitionName: 'Inter-Faculty Cup',
    interactions: {
      likesCount: 112,
      repostsCount: 18,
      commentsCount: 7,
      viewsCount: 890,
      bookmarksCount: 14,
    },
  },
  {
    id: 'art-3',
    headline: 'TRANSFER RUMOUR: Maragoli Strikers Target Campus Top Scorer Ahead of Window',
    subtitle: 'Scouts spotted at Thursday match as mid-season talks accelerate.',
    body: 'Reliable campus insiders report that Maragoli FC management has submitted an official query regarding player availability ahead of the mid-season transfer window.',
    category: 'transfer_rumour',
    timestamp: '3h ago',
    publishedAt: new Date().toISOString(),
    isToday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    images: ['https://images.unsplash.com/photo-1517649763962-0c623266010b?w=800&auto=format&fit=crop&q=80'],
    status: 'published',
    viewsCount: 2150,
    teamId: 'team-5',
    teamName: 'Maragoli Strikers',
    competitionId: 'comp-1',
    competitionName: 'Egerton Premier League',
    interactions: {
      likesCount: 310,
      repostsCount: 88,
      commentsCount: 42,
      viewsCount: 2150,
      bookmarksCount: 65,
    },
  },
  {
    id: 'art-4',
    headline: 'COACH INTERVIEW: "Our Defensive Line Is Stronger Than Ever", Says Coach Ochieng',
    subtitle: 'Exclusive post-training breakdown before the upcoming derby.',
    body: 'In an exclusive sit-down at Kilimo Gym, Coach Ochieng shared insights into Tatton FC tactical preparation and squad fitness management.',
    category: 'coach_interview',
    timestamp: 'Yesterday',
    publishedAt: new Date(Date.now() - 86400000).toISOString(),
    isYesterday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    images: ['https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&auto=format&fit=crop&q=80'],
    status: 'published',
    viewsCount: 3410,
    teamId: 'team-1',
    teamName: 'Tatton FC',
    competitionId: 'comp-1',
    competitionName: 'Egerton Premier League',
    interactions: {
      likesCount: 430,
      repostsCount: 95,
      commentsCount: 28,
      viewsCount: 3410,
      bookmarksCount: 82,
    },
  },
  {
    id: 'art-draft-1',
    headline: 'INJURY UPDATE: Medical Stars Midfielder Cleared for Weekend Fixture',
    subtitle: 'Scan results confirm minor ankle strain with full recovery expected.',
    body: 'Medical staff have confirmed that star midfielder Kamau suffered only a low-grade strain and will resume light squad training this afternoon.',
    category: 'injury_update',
    timestamp: 'Drafted 2h ago',
    publishedAt: new Date().toISOString(),
    isToday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    status: 'draft',
    viewsCount: 0,
    teamId: 'team-6',
    teamName: 'Medical Stars',
    competitionId: 'comp-1',
    competitionName: 'Egerton Premier League',
  },
  {
    id: 'art-flagged-1',
    headline: 'DISPUTED REPORT: Alleged Match Scheduling Conflict for Round 14',
    subtitle: 'Notice issued by League Administration regarding date overlap.',
    body: 'Controversy emerged earlier regarding fixture venues for upcoming Round 14 games across Pavilion and Njoro Grounds.',
    category: 'league_news',
    timestamp: 'Flagged today',
    publishedAt: new Date().toISOString(),
    isToday: true,
    authorName: 'Alex Mercer',
    authorHandle: '@alexmercer',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    isVerified: true,
    roleBadge: 'Lead Sports Correspondent',
    status: 'disputed',
    disputeReason: 'Pending official confirmation from FA Fixture Committee.',
    viewsCount: 650,
    competitionId: 'comp-1',
    competitionName: 'Egerton Premier League',
  },
];

export const INITIAL_PERFORMANCE: PerformanceMetrics = {
  articlesToday: 3,
  articlesThisWeek: 12,
  articlesThisMonth: 48,
  publishedCount: 42,
  draftsCount: 5,
  flaggedCount: 1,
  impressions: 148500,
  engagementRate: 7.8,
  reads: 92400,
  avgReadTime: '2m 18s',
  shares: 3420,
  topArticle: 'Tatton FC Edge Njoro City 2-1 in Derby Thriller',
  topCompetition: 'Egerton Premier League',
  mostCoveredTeam: 'Tatton FC',
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    type: 'like',
    actorName: 'Coach Ochieng',
    targetArticleTitle: 'Tatton FC Edge Njoro City 2-1',
    message: 'liked your breaking match report.',
    timestamp: '15m ago',
    isRead: false,
  },
  {
    id: 'notif-2',
    type: 'dispute',
    actorName: 'League Administrator',
    targetArticleTitle: 'Alleged Match Scheduling Conflict',
    message: 'flagged your article for administrative verification.',
    timestamp: '2h ago',
    isRead: false,
  },
];
