import { Player, Manager, FormationType, TeamData } from './types';
import { FLAGS, CRESTS, getPlayerAvatar } from './assets';

export const INITIAL_MANAGER: Manager = {
  name: 'Damia Granero',
  photoUrl: getPlayerAvatar('Damia Granero', '#ebd0b9', '#191c20', 'slick', true, '#1b253b'),
  proficiencies: {
    'Possession Game': 70,
    'Quick Counter': 70,
    'Long Ball Counter': 70,
    'Out Wide': 70,
    'Long Ball': 70,
  },
};

export const INITIAL_STARTING_XI: Player[] = [
  {
    id: 'kane',
    name: 'H. Kane',
    number: 9,
    position: 'CF',
    defaultPosition: 'CF',
    rating: 86,
    flagUrl: FLAGS.england,
    photoUrl: getPlayerAvatar('Harry Kane', '#fae1cc', '#9e793e', 'parted', true, '#ffffff'),
    cardTheme: 'purple',
    coord: { x: 48.5, y: 7 },
  },
  {
    id: 'messi',
    name: 'L. Messi',
    number: 10,
    position: 'AMF',
    defaultPosition: 'AMF',
    rating: 85,
    flagUrl: FLAGS.argentina,
    photoUrl: getPlayerAvatar('Lionel Messi', '#f0cfb3', '#4a3319', 'short', true, '#75aadb'),
    cardTheme: 'purple',
    coord: { x: 48.5, y: 31 },
  },
  {
    id: 'camavinga',
    name: 'E. Camavinga',
    number: 12,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 84,
    flagUrl: FLAGS.france,
    photoUrl: getPlayerAvatar('Eduardo Camavinga', '#4e3325', '#080808', 'curly', false, '#002654'),
    cardTheme: 'purple',
    coord: { x: 29, y: 49 },
  },
  {
    id: 'enzo',
    name: 'E. Fernández',
    number: 8,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 83,
    flagUrl: FLAGS.argentina,
    photoUrl: getPlayerAvatar('Enzo Fernandez', '#f4d2b8', '#1c1c1c', 'undercut', false, '#75aadb'),
    cardTheme: 'purple',
    coord: { x: 39.5, y: 51 },
  },
  {
    id: 'caicedo',
    name: 'M. Caicedo',
    number: 25,
    position: 'DMF',
    defaultPosition: 'DMF',
    rating: 81,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Moises Caicedo', '#422a1d', '#000000', 'buzz', false, '#0057b8'),
    cardTheme: 'black',
    coord: { x: 51.5, y: 51 },
  },
  {
    id: 'valverde',
    name: 'F. Valverde',
    number: 15,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 82,
    clubLogoUrl: CRESTS.realMadrid,
    photoUrl: getPlayerAvatar('Federico Valverde', '#fae1cc', '#3b2f2f', 'short', true, '#ffffff'),
    cardTheme: 'black',
    coord: { x: 65, y: 49 },
  },
  {
    id: 'theo',
    name: 'T. Hernández',
    number: 19,
    position: 'LB',
    defaultPosition: 'LB',
    rating: 77,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Theo Hernandez', '#ebd0b9', '#1a1a1a', 'undercut', true, '#d00000'),
    cardTheme: 'black',
    coord: { x: 32, y: 71 },
  },
  {
    id: 'bremer',
    name: 'Bremer',
    number: 3,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 80,
    clubLogoUrl: CRESTS.inter,
    photoUrl: getPlayerAvatar('Gleison Bremer', '#66432e', '#0a0a0a', 'buzz', true, '#001ea0'),
    cardTheme: 'black',
    coord: { x: 42, y: 71 },
  },
  {
    id: 'mancini',
    name: 'G. Mancini',
    number: 23,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 80,
    clubLogoUrl: CRESTS.roma,
    photoUrl: getPlayerAvatar('Gianluca Mancini', '#eed1ba', '#241b14', 'short', true, '#8e1f2f'),
    cardTheme: 'epic',
    coord: { x: 54.5, y: 71 },
  },
  {
    id: 'trent',
    name: 'T. Alexander-Arnold',
    number: 66,
    position: 'RB',
    defaultPosition: 'RB',
    rating: 84,
    flagUrl: FLAGS.england,
    photoUrl: getPlayerAvatar('Trent Alexander-Arnold', '#583a27', '#111111', 'curly', false, '#ffffff'),
    cardTheme: 'purple',
    coord: { x: 68.5, y: 72 },
  },
  {
    id: 'donnarumma',
    name: 'G. Donnarumma',
    number: 99,
    position: 'GK',
    defaultPosition: 'GK',
    rating: 83,
    clubLogoUrl: CRESTS.psg,
    photoUrl: getPlayerAvatar('Gianluigi Donnarumma', '#ebd1be', '#2c1e13', 'short', true, '#001c3d'),
    cardTheme: 'purple',
    isCaptain: true,
    coord: { x: 49.5, y: 88 },
  },
];

export const INITIAL_SUBSTITUTES: Player[] = [
  {
    id: 'sub_1',
    name: 'M. Merino',
    number: 14,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 76,
    clubLogoUrl: CRESTS.genericClub1,
    photoUrl: getPlayerAvatar('Merino', '#f5dcce', '#2b1b11', 'parted', false, '#4b0082'),
    cardTheme: 'black',
  },
  {
    id: 'sub_2',
    name: 'M. Depay',
    number: 11,
    position: 'CF',
    defaultPosition: 'CF',
    rating: 78,
    clubLogoUrl: CRESTS.genericClub2,
    photoUrl: getPlayerAvatar('Depay', '#6e472e', '#050505', 'undercut', true, '#004080'),
    cardTheme: 'black',
  },
  {
    id: 'sub_3',
    name: 'P. Kalulu',
    number: 20,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 59,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Kalulu', '#523422', '#000000', 'buzz', false, '#d00000'),
    cardTheme: 'black',
  },
  {
    id: 'sub_4',
    name: 'M. Thiaw',
    number: 28,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 60,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Thiaw', '#5c3d28', '#000000', 'buzz', false, '#d00000'),
    cardTheme: 'black',
  },
  {
    id: 'sub_5',
    name: 'B. Gilmour',
    number: 27,
    position: 'AMF',
    defaultPosition: 'AMF',
    rating: 63,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Gilmour', '#fce2d2', '#6b4f2c', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_6',
    name: 'Son Heung-min',
    number: 7,
    position: 'LWF',
    defaultPosition: 'LWF',
    rating: 79,
    flagUrl: FLAGS.korea,
    photoUrl: getPlayerAvatar('Son Heung-min', '#fae1cc', '#121212', 'parted', false, '#ffffff'),
    cardTheme: 'black',
  },
  {
    id: 'sub_7',
    name: 'E. Ferguson',
    number: 28,
    position: 'LMF',
    defaultPosition: 'LMF',
    rating: 60,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Ferguson', '#fae5d4', '#4a3b2b', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_8',
    name: 'T. Lamptey',
    number: 2,
    position: 'RB',
    defaultPosition: 'RB',
    rating: 61,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Lamptey', '#4f3322', '#000000', 'buzz', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_9',
    name: 'J. Enciso',
    number: 10,
    position: 'RWF',
    defaultPosition: 'RWF',
    rating: 59,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Enciso', '#ecd1b8', '#2b1b11', 'parted', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_10',
    name: 'F. Buonanotte',
    number: 40,
    position: 'SS',
    defaultPosition: 'SS',
    rating: 56,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Buonanotte', '#f3d5c1', '#332314', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
];

export const TEAMS_DATA: Record<string, TeamData> = {
  man_united: {
    id: 'man_united',
    name: 'Manchester United',
    shortName: 'Man United',
    crestUrl: CRESTS.manUnited,
    formation: '4-4-1-1',
    playstyle: 'Quick Counter',
    manager: INITIAL_MANAGER,
    startingXI: INITIAL_STARTING_XI,
    substitutes: INITIAL_SUBSTITUTES,
  },
  real_madrid: {
    id: 'real_madrid',
    name: 'Real Madrid',
    shortName: 'Real Madrid',
    crestUrl: CRESTS.realMadrid,
    formation: '4-3-3',
    playstyle: 'Possession Game',
    manager: {
      name: 'Carlo Ancelotti',
      photoUrl: getPlayerAvatar('Carlo Ancelotti', '#fae1cc', '#e2e8f0', 'parted', false, '#ffffff'),
      proficiencies: {
        'Possession Game': 85,
        'Quick Counter': 82,
        'Long Ball Counter': 78,
        'Out Wide': 75,
        'Long Ball': 70,
      },
    },
    startingXI: [
      {
        id: 'rm_1',
        name: 'K. Mbappé',
        number: 9,
        position: 'CF',
        defaultPosition: 'CF',
        rating: 91,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Kylian Mbappe', '#54392b', '#050505', 'buzz', false, '#ffffff'),
        cardTheme: 'epic',
        coord: { x: 48.5, y: 8 },
      },
      {
        id: 'rm_2',
        name: 'Vinícius Jr.',
        number: 7,
        position: 'LWF',
        defaultPosition: 'LWF',
        rating: 90,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Vinicius Jr', '#382318', '#000000', 'curly', false, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 30, y: 15 },
      },
      {
        id: 'rm_3',
        name: 'Rodrygo',
        number: 11,
        position: 'RWF',
        defaultPosition: 'RWF',
        rating: 87,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Rodrygo', '#42281a', '#0a0a0a', 'short', false, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 67, y: 15 },
      },
      {
        id: 'rm_4',
        name: 'J. Bellingham',
        number: 5,
        position: 'CMF',
        defaultPosition: 'CMF',
        rating: 89,
        flagUrl: FLAGS.england,
        photoUrl: getPlayerAvatar('Jude Bellingham', '#4a3325', '#0f0f0f', 'short', false, '#ffffff'),
        cardTheme: 'epic',
        coord: { x: 34, y: 45 },
      },
      {
        id: 'rm_5',
        name: 'A. Tchouaméni',
        number: 14,
        position: 'DMF',
        defaultPosition: 'DMF',
        rating: 85,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Aurelien Tchouameni', '#3d2518', '#000000', 'buzz', false, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 48.5, y: 53 },
      },
      {
        id: 'rm_6',
        name: 'F. Valverde',
        number: 8,
        position: 'CMF',
        defaultPosition: 'CMF',
        rating: 88,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Federico Valverde', '#fae1cc', '#3b2f2f', 'short', true, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 63, y: 45 },
      },
      {
        id: 'rm_7',
        name: 'F. Mendy',
        number: 23,
        position: 'LB',
        defaultPosition: 'LB',
        rating: 82,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Ferland Mendy', '#382318', '#000000', 'buzz', false, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 32, y: 71 },
      },
      {
        id: 'rm_8',
        name: 'A. Rüdiger',
        number: 22,
        position: 'CB',
        defaultPosition: 'CB',
        rating: 86,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Antonio Rudiger', '#2c1a11', '#000000', 'buzz', true, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 42, y: 71 },
      },
      {
        id: 'rm_9',
        name: 'Éder Militão',
        number: 3,
        position: 'CB',
        defaultPosition: 'CB',
        rating: 85,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Eder Militao', '#42281a', '#000000', 'undercut', true, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 54.5, y: 71 },
      },
      {
        id: 'rm_10',
        name: 'D. Carvajal',
        number: 2,
        position: 'RB',
        defaultPosition: 'RB',
        rating: 85,
        flagUrl: FLAGS.spain,
        photoUrl: getPlayerAvatar('Dani Carvajal', '#f0cfb3', '#332314', 'short', true, '#ffffff'),
        cardTheme: 'purple',
        isCaptain: true,
        coord: { x: 68.5, y: 72 },
      },
      {
        id: 'rm_11',
        name: 'T. Courtois',
        number: 1,
        position: 'GK',
        defaultPosition: 'GK',
        rating: 90,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Thibaut Courtois', '#fae1cc', '#241b14', 'short', true, '#0f172a'),
        cardTheme: 'epic',
        coord: { x: 49.5, y: 88 },
      },
    ],
    substitutes: [
      { id: 'rm_s1', name: 'L. Modrić', number: 10, position: 'CMF', defaultPosition: 'CMF', rating: 86, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Luka Modric', '#fae1cc', '#9e793e', 'parted', false, '#ffffff'), cardTheme: 'epic' },
      { id: 'rm_s2', name: 'E. Camavinga', number: 6, position: 'CMF', defaultPosition: 'CMF', rating: 85, flagUrl: FLAGS.france, photoUrl: getPlayerAvatar('Eduardo Camavinga', '#4e3325', '#080808', 'curly', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s3', name: 'B. Díaz', number: 21, position: 'AMF', defaultPosition: 'AMF', rating: 82, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Brahim Diaz', '#eed1ba', '#1a1a1a', 'short', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s4', name: 'Endrick', number: 16, position: 'CF', defaultPosition: 'CF', rating: 80, flagUrl: FLAGS.brazil, photoUrl: getPlayerAvatar('Endrick', '#3d2518', '#000000', 'buzz', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s5', name: 'A. Güler', number: 15, position: 'AMF', defaultPosition: 'AMF', rating: 81, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Arda Guler', '#f5dcce', '#2b1b11', 'parted', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s6', name: 'D. Alaba', number: 4, position: 'CB', defaultPosition: 'CB', rating: 83, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('David Alaba', '#583a27', '#000000', 'buzz', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s7', name: 'L. Vázquez', number: 17, position: 'RB', defaultPosition: 'RB', rating: 80, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Lucas Vazquez', '#f0cfb3', '#332314', 'short', false, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s8', name: 'Fran García', number: 20, position: 'LB', defaultPosition: 'LB', rating: 79, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Fran Garcia', '#eed1ba', '#241b14', 'short', false, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s9', name: 'D. Ceballos', number: 19, position: 'CMF', defaultPosition: 'CMF', rating: 78, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Dani Ceballos', '#fae1cc', '#241b14', 'short', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s10', name: 'A. Lunin', number: 13, position: 'GK', defaultPosition: 'GK', rating: 82, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Andriy Lunin', '#fae1cc', '#8c5828', 'short', false, '#0f172a'), cardTheme: 'black' },
    ],
  },
  argentina: {
    id: 'argentina',
    name: 'Argentina',
    shortName: 'Argentina',
    crestUrl: CRESTS.argentinaCrest,
    formation: '4-3-3',
    playstyle: 'Quick Counter',
    manager: {
      name: 'Lionel Scaloni',
      photoUrl: getPlayerAvatar('Lionel Scaloni', '#ebd0b9', '#191c20', 'short', true, '#75aadb'),
      proficiencies: {
        'Possession Game': 82,
        'Quick Counter': 86,
        'Long Ball Counter': 80,
        'Out Wide': 74,
        'Long Ball': 72,
      },
    },
    startingXI: [
      { id: 'arg_1', name: 'J. Álvarez', number: 9, position: 'CF', defaultPosition: 'CF', rating: 88, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Julian Alvarez', '#f4d2b8', '#2b1b11', 'short', false, '#75aadb'), cardTheme: 'epic', coord: { x: 48.5, y: 8 } },
      { id: 'arg_2', name: 'L. Messi', number: 10, position: 'LWF', defaultPosition: 'LWF', rating: 92, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Lionel Messi', '#f0cfb3', '#4a3319', 'short', true, '#75aadb'), cardTheme: 'epic', isCaptain: true, coord: { x: 30, y: 15 } },
      { id: 'arg_3', name: 'L. Martínez', number: 22, position: 'RWF', defaultPosition: 'RWF', rating: 89, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Lautaro Martinez', '#ebd0b9', '#111111', 'undercut', true, '#75aadb'), cardTheme: 'purple', coord: { x: 67, y: 15 } },
      { id: 'arg_4', name: 'A. Mac Allister', number: 20, position: 'CMF', defaultPosition: 'CMF', rating: 87, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Alexis Mac Allister', '#fae1cc', '#8c5828', 'parted', true, '#75aadb'), cardTheme: 'purple', coord: { x: 34, y: 45 } },
      { id: 'arg_5', name: 'E. Fernández', number: 24, position: 'DMF', defaultPosition: 'DMF', rating: 86, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Enzo Fernandez', '#f4d2b8', '#1c1c1c', 'undercut', false, '#75aadb'), cardTheme: 'purple', coord: { x: 48.5, y: 53 } },
      { id: 'arg_6', name: 'R. De Paul', number: 7, position: 'CMF', defaultPosition: 'CMF', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Rodrigo De Paul', '#eed1ba', '#3b2f2f', 'undercut', true, '#75aadb'), cardTheme: 'black', coord: { x: 63, y: 45 } },
      { id: 'arg_7', name: 'N. Tagliafico', number: 3, position: 'LB', defaultPosition: 'LB', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nicolas Tagliafico', '#f5dcce', '#2b1b11', 'short', false, '#75aadb'), cardTheme: 'black', coord: { x: 32, y: 71 } },
      { id: 'arg_8', name: 'C. Romero', number: 13, position: 'CB', defaultPosition: 'CB', rating: 87, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Cristian Romero', '#ebd0b9', '#111111', 'short', false, '#75aadb'), cardTheme: 'purple', coord: { x: 42, y: 71 } },
      { id: 'arg_9', name: 'N. Otamendi', number: 19, position: 'CB', defaultPosition: 'CB', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nicolas Otamendi', '#ebd0b9', '#111111', 'undercut', true, '#75aadb'), cardTheme: 'black', coord: { x: 54.5, y: 71 } },
      { id: 'arg_10', name: 'N. Molina', number: 26, position: 'RB', defaultPosition: 'RB', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nahuel Molina', '#f4d2b8', '#241b14', 'short', false, '#75aadb'), cardTheme: 'black', coord: { x: 68.5, y: 72 } },
      { id: 'arg_11', name: 'E. Martínez', number: 23, position: 'GK', defaultPosition: 'GK', rating: 89, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Emiliano Martinez', '#fae1cc', '#241b14', 'short', false, '#0a192f'), cardTheme: 'epic', coord: { x: 49.5, y: 88 } },
    ],
    substitutes: [
      { id: 'arg_s1', name: 'A. Garnacho', number: 17, position: 'LWF', defaultPosition: 'LWF', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Alejandro Garnacho', '#fae1cc', '#d1b15c', 'undercut', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s2', name: 'P. Dybala', number: 21, position: 'SS', defaultPosition: 'SS', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Paulo Dybala', '#fae1cc', '#1a1a1a', 'parted', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s3', name: 'N. González', number: 15, position: 'LWF', defaultPosition: 'LWF', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nicolas Gonzalez', '#eed1ba', '#1a1a1a', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s4', name: 'L. Paredes', number: 5, position: 'DMF', defaultPosition: 'DMF', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Leandro Paredes', '#ebd0b9', '#111111', 'short', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s5', name: 'G. Lo Celso', number: 16, position: 'CMF', defaultPosition: 'CMF', rating: 81, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Giovani Lo Celso', '#fae1cc', '#3b2f2f', 'short', false, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s6', name: 'M. Acuña', number: 8, position: 'LB', defaultPosition: 'LB', rating: 80, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Marcos Acuna', '#ebd0b9', '#111111', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s7', name: 'Lisandro M.', number: 25, position: 'CB', defaultPosition: 'CB', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Lisandro Martinez', '#fae1cc', '#111111', 'undercut', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s8', name: 'G. Pezzella', number: 6, position: 'CB', defaultPosition: 'CB', rating: 78, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('German Pezzella', '#ebd0b9', '#241b14', 'short', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s9', name: 'G. Montiel', number: 4, position: 'RB', defaultPosition: 'RB', rating: 79, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Gonzalo Montiel', '#ebd0b9', '#111111', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s10', name: 'G. Rulli', number: 1, position: 'GK', defaultPosition: 'GK', rating: 80, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Geronimo Rulli', '#fae1cc', '#241b14', 'short', true, '#0a192f'), cardTheme: 'black' },
    ],
  },
};

export const FORMATIONS: Record<FormationType, { name: FormationType; coords: { position: Player['position']; x: number; y: number }[] }> = {
  '4-4-1-1': {
    name: '4-4-1-1',
    coords: [
      { position: 'CF', x: 48.5, y: 7 },
      { position: 'AMF', x: 48.5, y: 31 },
      { position: 'CMF', x: 29, y: 49 },
      { position: 'CMF', x: 39.5, y: 51 },
      { position: 'DMF', x: 51.5, y: 51 },
      { position: 'CMF', x: 65, y: 49 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-3-3': {
    name: '4-3-3',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LWF', x: 30, y: 15 },
      { position: 'RWF', x: 67, y: 15 },
      { position: 'CMF', x: 34, y: 45 },
      { position: 'DMF', x: 48.5, y: 53 },
      { position: 'CMF', x: 63, y: 45 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-2-1-3': {
    name: '4-2-1-3',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LWF', x: 30, y: 16 },
      { position: 'RWF', x: 67, y: 16 },
      { position: 'AMF', x: 48.5, y: 35 },
      { position: 'DMF', x: 38, y: 52 },
      { position: 'DMF', x: 58, y: 52 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-2-2-2': {
    name: '4-2-2-2',
    coords: [
      { position: 'CF', x: 39, y: 10 },
      { position: 'CF', x: 57, y: 10 },
      { position: 'LMF', x: 28, y: 38 },
      { position: 'RMF', x: 68, y: 38 },
      { position: 'DMF', x: 39, y: 54 },
      { position: 'DMF', x: 57, y: 54 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '3-2-4-1': {
    name: '3-2-4-1',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LMF', x: 26, y: 33 },
      { position: 'AMF', x: 41, y: 30 },
      { position: 'AMF', x: 56, y: 30 },
      { position: 'RMF', x: 70, y: 33 },
      { position: 'DMF', x: 40, y: 52 },
      { position: 'DMF', x: 57, y: 52 },
      { position: 'CB', x: 33, y: 72 },
      { position: 'CB', x: 48.5, y: 72 },
      { position: 'CB', x: 64, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
};
