import { Player, Manager, FormationType, TeamData } from './types';
import { FLAGS, CRESTS, getPlayerAvatar } from './assets';

export const INITIAL_MANAGER: Manager = {
  name: 'Coach B. Ombati',
  photoUrl: getPlayerAvatar('Coach Ombati', '#ebd0b9', '#191c20', 'slick', true, '#1b253b'),
  proficiencies: {
    'Possession Game': 70,
    'Quick Counter': 70,
    'Long Ball Counter': 70,
    'Out Wide': 70,
    'Long Ball': 70,
  },
};

export const INITIAL_STARTING_XI: Player[] = [
  {
    id: 'kipchoge',
    name: 'H. Kipchoge',
    number: 9,
    position: 'CF',
    defaultPosition: 'CF',
    rating: 86,
    flagUrl: FLAGS.england,
    photoUrl: getPlayerAvatar('Hillary Kipchoge', '#fae1cc', '#9e793e', 'parted', true, '#ffffff'),
    cardTheme: 'purple',
    coord: { x: 48.5, y: 7 },
  },
  {
    id: 'otieno',
    name: 'L. Otieno',
    number: 10,
    position: 'AMF',
    defaultPosition: 'AMF',
    rating: 85,
    flagUrl: FLAGS.argentina,
    photoUrl: getPlayerAvatar('Lucas Otieno', '#f0cfb3', '#4a3319', 'short', true, '#75aadb'),
    cardTheme: 'purple',
    coord: { x: 48.5, y: 31 },
  },
  {
    id: 'kamau',
    name: 'E. Kamau',
    number: 12,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 84,
    flagUrl: FLAGS.france,
    photoUrl: getPlayerAvatar('Edwin Kamau', '#4e3325', '#080808', 'curly', false, '#002654'),
    cardTheme: 'purple',
    coord: { x: 29, y: 49 },
  },
  {
    id: 'kiprono',
    name: 'E. Kiprono',
    number: 8,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 83,
    flagUrl: FLAGS.argentina,
    photoUrl: getPlayerAvatar('Eric Kiprono', '#f4d2b8', '#1c1c1c', 'undercut', false, '#75aadb'),
    cardTheme: 'purple',
    coord: { x: 39.5, y: 51 },
  },
  {
    id: 'wanjala',
    name: 'M. Wanjala',
    number: 25,
    position: 'DMF',
    defaultPosition: 'DMF',
    rating: 81,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Michael Wanjala', '#422a1d', '#000000', 'buzz', false, '#0057b8'),
    cardTheme: 'black',
    coord: { x: 51.5, y: 51 },
  },
  {
    id: 'ochieng',
    name: 'F. Ochieng',
    number: 15,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 82,
    clubLogoUrl: CRESTS.realMadrid,
    photoUrl: getPlayerAvatar('Felix Ochieng', '#fae1cc', '#3b2f2f', 'short', true, '#ffffff'),
    cardTheme: 'black',
    coord: { x: 65, y: 49 },
  },
  {
    id: 'mwangi',
    name: 'T. Mwangi',
    number: 19,
    position: 'LB',
    defaultPosition: 'LB',
    rating: 77,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Titus Mwangi', '#ebd0b9', '#1a1a1a', 'undercut', true, '#d00000'),
    cardTheme: 'black',
    coord: { x: 32, y: 71 },
  },
  {
    id: 'kipruto',
    name: 'G. Kipruto',
    number: 3,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 80,
    clubLogoUrl: CRESTS.inter,
    photoUrl: getPlayerAvatar('Gideon Kipruto', '#66432e', '#0a0a0a', 'buzz', true, '#001ea0'),
    cardTheme: 'black',
    coord: { x: 42, y: 71 },
  },
  {
    id: 'maina',
    name: 'G. Maina',
    number: 23,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 80,
    clubLogoUrl: CRESTS.roma,
    photoUrl: getPlayerAvatar('George Maina', '#eed1ba', '#241b14', 'short', true, '#8e1f2f'),
    cardTheme: 'epic',
    coord: { x: 54.5, y: 71 },
  },
  {
    id: 'cheruiyot',
    name: 'T. Cheruiyot',
    number: 66,
    position: 'RB',
    defaultPosition: 'RB',
    rating: 84,
    flagUrl: FLAGS.england,
    photoUrl: getPlayerAvatar('Timothy Cheruiyot', '#583a27', '#111111', 'curly', false, '#ffffff'),
    cardTheme: 'purple',
    coord: { x: 68.5, y: 72 },
  },
  {
    id: 'kimutai',
    name: 'D. Kimutai',
    number: 99,
    position: 'GK',
    defaultPosition: 'GK',
    rating: 83,
    clubLogoUrl: CRESTS.psg,
    photoUrl: getPlayerAvatar('Dennis Kimutai', '#ebd1be', '#2c1e13', 'short', true, '#001c3d'),
    cardTheme: 'purple',
    isCaptain: true,
    coord: { x: 49.5, y: 88 },
  },
];

export const INITIAL_SUBSTITUTES: Player[] = [
  {
    id: 'sub_1',
    name: 'M. Kimani',
    number: 14,
    position: 'CMF',
    defaultPosition: 'CMF',
    rating: 76,
    clubLogoUrl: CRESTS.genericClub1,
    photoUrl: getPlayerAvatar('Martin Kimani', '#f5dcce', '#2b1b11', 'parted', false, '#4b0082'),
    cardTheme: 'black',
  },
  {
    id: 'sub_2',
    name: 'M. Baraza',
    number: 11,
    position: 'CF',
    defaultPosition: 'CF',
    rating: 78,
    clubLogoUrl: CRESTS.genericClub2,
    photoUrl: getPlayerAvatar('Moses Baraza', '#6e472e', '#050505', 'undercut', true, '#004080'),
    cardTheme: 'black',
  },
  {
    id: 'sub_3',
    name: 'P. Korir',
    number: 20,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 59,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Peter Korir', '#523422', '#000000', 'buzz', false, '#d00000'),
    cardTheme: 'black',
  },
  {
    id: 'sub_4',
    name: 'M. Odhiambo',
    number: 28,
    position: 'CB',
    defaultPosition: 'CB',
    rating: 60,
    clubLogoUrl: CRESTS.milan,
    photoUrl: getPlayerAvatar('Mark Odhiambo', '#5c3d28', '#000000', 'buzz', false, '#d00000'),
    cardTheme: 'black',
  },
  {
    id: 'sub_5',
    name: 'B. Kiprop',
    number: 27,
    position: 'AMF',
    defaultPosition: 'AMF',
    rating: 63,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Brian Kiprop', '#fce2d2', '#6b4f2c', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_6',
    name: 'S. Mutiso',
    number: 7,
    position: 'LWF',
    defaultPosition: 'LWF',
    rating: 79,
    flagUrl: FLAGS.korea,
    photoUrl: getPlayerAvatar('Stephen Mutiso', '#fae1cc', '#121212', 'parted', false, '#ffffff'),
    cardTheme: 'black',
  },
  {
    id: 'sub_7',
    name: 'E. Koech',
    number: 28,
    position: 'LMF',
    defaultPosition: 'LMF',
    rating: 60,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Emmanuel Koech', '#fae5d4', '#4a3b2b', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_8',
    name: 'T. Kariuki',
    number: 2,
    position: 'RB',
    defaultPosition: 'RB',
    rating: 61,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Thomas Kariuki', '#4f3322', '#000000', 'buzz', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_9',
    name: 'J. Kibet',
    number: 10,
    position: 'RWF',
    defaultPosition: 'RWF',
    rating: 59,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Joel Kibet', '#ecd1b8', '#2b1b11', 'parted', false, '#0057b8'),
    cardTheme: 'black',
  },
  {
    id: 'sub_10',
    name: 'F. Rotich',
    number: 40,
    position: 'SS',
    defaultPosition: 'SS',
    rating: 56,
    clubLogoUrl: CRESTS.brighton,
    photoUrl: getPlayerAvatar('Francis Rotich', '#f3d5c1', '#332314', 'short', false, '#0057b8'),
    cardTheme: 'black',
  },
];

export const TEAMS_DATA: Record<string, TeamData> = {
  man_united: {
    id: 'man_united',
    name: 'Egerton Red Hawks',
    shortName: 'Egerton Hawks',
    crestUrl: CRESTS.manUnited,
    formation: '4-4-1-1',
    playstyle: 'Quick Counter',
    manager: INITIAL_MANAGER,
    startingXI: INITIAL_STARTING_XI,
    substitutes: INITIAL_SUBSTITUTES,
  },
  real_madrid: {
    id: 'real_madrid',
    name: 'Njoro Titans FC',
    shortName: 'Njoro Titans',
    crestUrl: CRESTS.realMadrid,
    formation: '4-3-3',
    playstyle: 'Possession Game',
    manager: {
      name: 'Coach C. Mutua',
      photoUrl: getPlayerAvatar('Coach Mutua', '#fae1cc', '#e2e8f0', 'parted', false, '#ffffff'),
      proficiencies: {
        'Possession Game': 85,
        'Quick Counter': 82,
        'Long Ball Counter': 78,
        'Out Wide': 75,
        'Long Ball': 70,
      },
    },
    startingXI: [
      {
        id: 'rm_1',
        name: 'K. Mutua',
        number: 9,
        position: 'CF',
        defaultPosition: 'CF',
        rating: 91,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Kevin Mutua', '#54392b', '#050505', 'buzz', false, '#ffffff'),
        cardTheme: 'epic',
        coord: { x: 48.5, y: 8 },
      },
      {
        id: 'rm_2',
        name: 'V. Omondi',
        number: 7,
        position: 'LWF',
        defaultPosition: 'LWF',
        rating: 90,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Victor Omondi', '#382318', '#000000', 'curly', false, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 30, y: 15 },
      },
      {
        id: 'rm_3',
        name: 'R. Baraza',
        number: 11,
        position: 'RWF',
        defaultPosition: 'RWF',
        rating: 87,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Robert Baraza', '#42281a', '#0a0a0a', 'short', false, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 67, y: 15 },
      },
      {
        id: 'rm_4',
        name: 'J. Kiptoo',
        number: 5,
        position: 'CMF',
        defaultPosition: 'CMF',
        rating: 89,
        flagUrl: FLAGS.england,
        photoUrl: getPlayerAvatar('Japheth Kiptoo', '#4a3325', '#0f0f0f', 'short', false, '#ffffff'),
        cardTheme: 'epic',
        coord: { x: 34, y: 45 },
      },
      {
        id: 'rm_5',
        name: 'A. Kipkemboi',
        number: 14,
        position: 'DMF',
        defaultPosition: 'DMF',
        rating: 85,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Allan Kipkemboi', '#3d2518', '#000000', 'buzz', false, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 48.5, y: 53 },
      },
      {
        id: 'rm_6',
        name: 'F. Koech',
        number: 8,
        position: 'CMF',
        defaultPosition: 'CMF',
        rating: 88,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Felix Koech', '#fae1cc', '#3b2f2f', 'short', true, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 63, y: 45 },
      },
      {
        id: 'rm_7',
        name: 'F. Njoroge',
        number: 23,
        position: 'LB',
        defaultPosition: 'LB',
        rating: 82,
        flagUrl: FLAGS.france,
        photoUrl: getPlayerAvatar('Francis Njoroge', '#382318', '#000000', 'buzz', false, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 32, y: 71 },
      },
      {
        id: 'rm_8',
        name: 'A. Ruto',
        number: 22,
        position: 'CB',
        defaultPosition: 'CB',
        rating: 86,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Arthur Ruto', '#2c1a11', '#000000', 'buzz', true, '#ffffff'),
        cardTheme: 'purple',
        coord: { x: 42, y: 71 },
      },
      {
        id: 'rm_9',
        name: 'E. Rotich',
        number: 3,
        position: 'CB',
        defaultPosition: 'CB',
        rating: 85,
        flagUrl: FLAGS.brazil,
        photoUrl: getPlayerAvatar('Evans Rotich', '#42281a', '#000000', 'undercut', true, '#ffffff'),
        cardTheme: 'black',
        coord: { x: 54.5, y: 71 },
      },
      {
        id: 'rm_10',
        name: 'D. Kariuki',
        number: 2,
        position: 'RB',
        defaultPosition: 'RB',
        rating: 85,
        flagUrl: FLAGS.spain,
        photoUrl: getPlayerAvatar('Daniel Kariuki', '#f0cfb3', '#332314', 'short', true, '#ffffff'),
        cardTheme: 'purple',
        isCaptain: true,
        coord: { x: 68.5, y: 72 },
      },
      {
        id: 'rm_11',
        name: 'T. Ondiek',
        number: 1,
        position: 'GK',
        defaultPosition: 'GK',
        rating: 90,
        clubLogoUrl: CRESTS.realMadrid,
        photoUrl: getPlayerAvatar('Thomas Ondiek', '#fae1cc', '#241b14', 'short', true, '#0f172a'),
        cardTheme: 'epic',
        coord: { x: 49.5, y: 88 },
      },
    ],
    substitutes: [
      { id: 'rm_s1', name: 'L. Mbugua', number: 10, position: 'CMF', defaultPosition: 'CMF', rating: 86, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Luke Mbugua', '#fae1cc', '#9e793e', 'parted', false, '#ffffff'), cardTheme: 'epic' },
      { id: 'rm_s2', name: 'E. Chege', number: 6, position: 'CMF', defaultPosition: 'CMF', rating: 85, flagUrl: FLAGS.france, photoUrl: getPlayerAvatar('Edwin Chege', '#4e3325', '#080808', 'curly', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s3', name: 'B. Wafula', number: 21, position: 'AMF', defaultPosition: 'AMF', rating: 82, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Brian Wafula', '#eed1ba', '#1a1a1a', 'short', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s4', name: 'E. Kipchumba', number: 16, position: 'CF', defaultPosition: 'CF', rating: 80, flagUrl: FLAGS.brazil, photoUrl: getPlayerAvatar('Emmanuel Kipchumba', '#3d2518', '#000000', 'buzz', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s5', name: 'A. Githinji', number: 15, position: 'AMF', defaultPosition: 'AMF', rating: 81, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Albert Githinji', '#f5dcce', '#2b1b11', 'parted', false, '#ffffff'), cardTheme: 'purple' },
      { id: 'rm_s6', name: 'D. Ambani', number: 4, position: 'CB', defaultPosition: 'CB', rating: 83, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('David Ambani', '#583a27', '#000000', 'buzz', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s7', name: 'L. Victor', number: 17, position: 'RB', defaultPosition: 'RB', rating: 80, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Lucas Victor', '#f0cfb3', '#332314', 'short', false, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s8', name: 'F. Gathua', number: 20, position: 'LB', defaultPosition: 'LB', rating: 79, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Fred Gathua', '#eed1ba', '#241b14', 'short', false, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s9', name: 'D. Chesire', number: 19, position: 'CMF', defaultPosition: 'CMF', rating: 78, flagUrl: FLAGS.spain, photoUrl: getPlayerAvatar('Denis Chesire', '#fae1cc', '#241b14', 'short', true, '#ffffff'), cardTheme: 'black' },
      { id: 'rm_s10', name: 'A. Lokuruka', number: 13, position: 'GK', defaultPosition: 'GK', rating: 82, clubLogoUrl: CRESTS.realMadrid, photoUrl: getPlayerAvatar('Andrew Lokuruka', '#fae1cc', '#8c5828', 'short', false, '#0f172a'), cardTheme: 'black' },
    ],
  },
  argentina: {
    id: 'argentina',
    name: 'Rift Valley All-Stars',
    shortName: 'RV Stars',
    crestUrl: CRESTS.argentinaCrest,
    formation: '4-3-3',
    playstyle: 'Quick Counter',
    manager: {
      name: 'Coach L. Sang',
      photoUrl: getPlayerAvatar('Coach Sang', '#ebd0b9', '#191c20', 'short', true, '#75aadb'),
      proficiencies: {
        'Possession Game': 82,
        'Quick Counter': 86,
        'Long Ball Counter': 80,
        'Out Wide': 74,
        'Long Ball': 72,
      },
    },
    startingXI: [
      { id: 'arg_1', name: 'J. Kibet', number: 9, position: 'CF', defaultPosition: 'CF', rating: 88, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Julius Kibet', '#f4d2b8', '#2b1b11', 'short', false, '#75aadb'), cardTheme: 'epic', coord: { x: 48.5, y: 8 } },
      { id: 'arg_2', name: 'L. Kimani', number: 10, position: 'LWF', defaultPosition: 'LWF', rating: 92, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Lawrence Kimani', '#f0cfb3', '#4a3319', 'short', true, '#75aadb'), cardTheme: 'epic', isCaptain: true, coord: { x: 30, y: 15 } },
      { id: 'arg_3', name: 'L. Korir', number: 22, position: 'RWF', defaultPosition: 'RWF', rating: 89, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Linus Korir', '#ebd0b9', '#111111', 'undercut', true, '#75aadb'), cardTheme: 'purple', coord: { x: 67, y: 15 } },
      { id: 'arg_4', name: 'A. Bett', number: 20, position: 'CMF', defaultPosition: 'CMF', rating: 87, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Amos Bett', '#fae1cc', '#8c5828', 'parted', true, '#75aadb'), cardTheme: 'purple', coord: { x: 34, y: 45 } },
      { id: 'arg_5', name: 'E. Chebet', number: 24, position: 'DMF', defaultPosition: 'DMF', rating: 86, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Ezekiel Chebet', '#f4d2b8', '#1c1c1c', 'undercut', false, '#75aadb'), cardTheme: 'purple', coord: { x: 48.5, y: 53 } },
      { id: 'arg_6', name: 'R. Kiprono', number: 7, position: 'CMF', defaultPosition: 'CMF', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Robert Kiprono', '#eed1ba', '#3b2f2f', 'undercut', true, '#75aadb'), cardTheme: 'black', coord: { x: 63, y: 45 } },
      { id: 'arg_7', name: 'N. Langat', number: 3, position: 'LB', defaultPosition: 'LB', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nicholas Langat', '#f5dcce', '#2b1b11', 'short', false, '#75aadb'), cardTheme: 'black', coord: { x: 32, y: 71 } },
      { id: 'arg_8', name: 'C. Rono', number: 13, position: 'CB', defaultPosition: 'CB', rating: 87, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Caleb Rono', '#ebd0b9', '#111111', 'short', false, '#75aadb'), cardTheme: 'purple', coord: { x: 42, y: 71 } },
      { id: 'arg_9', name: 'N. Tanui', number: 19, position: 'CB', defaultPosition: 'CB', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Noah Tanui', '#ebd0b9', '#111111', 'undercut', true, '#75aadb'), cardTheme: 'black', coord: { x: 54.5, y: 71 } },
      { id: 'arg_10', name: 'N. Komen', number: 26, position: 'RB', defaultPosition: 'RB', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nathan Komen', '#f4d2b8', '#241b14', 'short', false, '#75aadb'), cardTheme: 'black', coord: { x: 68.5, y: 72 } },
      { id: 'arg_11', name: 'E. Yego', number: 23, position: 'GK', defaultPosition: 'GK', rating: 89, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Elijah Yego', '#fae1cc', '#241b14', 'short', false, '#0a192f'), cardTheme: 'epic', coord: { x: 49.5, y: 88 } },
    ],
    substitutes: [
      { id: 'arg_s1', name: 'A. Gitonga', number: 17, position: 'LWF', defaultPosition: 'LWF', rating: 83, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Antony Gitonga', '#fae1cc', '#d1b15c', 'undercut', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s2', name: 'P. Deng', number: 21, position: 'SS', defaultPosition: 'SS', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Peter Deng', '#fae1cc', '#1a1a1a', 'parted', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s3', name: 'N. Gikonyo', number: 15, position: 'LWF', defaultPosition: 'LWF', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Nelson Gikonyo', '#eed1ba', '#1a1a1a', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s4', name: 'L. Peter', number: 5, position: 'DMF', defaultPosition: 'DMF', rating: 82, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Leonard Peter', '#ebd0b9', '#111111', 'short', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s5', name: 'G. Lengusuranga', number: 16, position: 'CMF', defaultPosition: 'CMF', rating: 81, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Geoffrey Lengusuranga', '#fae1cc', '#3b2f2f', 'short', false, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s6', name: 'M. Asande', number: 8, position: 'LB', defaultPosition: 'LB', rating: 80, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Meshack Asande', '#ebd0b9', '#111111', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s7', name: 'L. Makori', number: 25, position: 'CB', defaultPosition: 'CB', rating: 85, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Laban Makori', '#fae1cc', '#111111', 'undercut', false, '#75aadb'), cardTheme: 'purple' },
      { id: 'arg_s8', name: 'G. Paul', number: 6, position: 'CB', defaultPosition: 'CB', rating: 78, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('George Paul', '#ebd0b9', '#241b14', 'short', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s9', name: 'G. Muriuki', number: 4, position: 'RB', defaultPosition: 'RB', rating: 79, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Gilbert Muriuki', '#ebd0b9', '#111111', 'buzz', true, '#75aadb'), cardTheme: 'black' },
      { id: 'arg_s10', name: 'G. Ronoh', number: 1, position: 'GK', defaultPosition: 'GK', rating: 80, flagUrl: FLAGS.argentina, photoUrl: getPlayerAvatar('Gideon Ronoh', '#fae1cc', '#241b14', 'short', true, '#0a192f'), cardTheme: 'black' },
    ],
  },
};

export const FORMATIONS: Record<FormationType, { name: FormationType; coords: { position: Player['position']; x: number; y: number }[] }> = {
  '4-4-1-1': {
    name: '4-4-1-1',
    coords: [
      { position: 'CF', x: 48.5, y: 7 },
      { position: 'AMF', x: 48.5, y: 31 },
      { position: 'CMF', x: 29, y: 49 },
      { position: 'CMF', x: 39.5, y: 51 },
      { position: 'DMF', x: 51.5, y: 51 },
      { position: 'CMF', x: 65, y: 49 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-3-3': {
    name: '4-3-3',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LWF', x: 30, y: 15 },
      { position: 'RWF', x: 67, y: 15 },
      { position: 'CMF', x: 34, y: 45 },
      { position: 'DMF', x: 48.5, y: 53 },
      { position: 'CMF', x: 63, y: 45 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-2-1-3': {
    name: '4-2-1-3',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LWF', x: 30, y: 16 },
      { position: 'RWF', x: 67, y: 16 },
      { position: 'AMF', x: 48.5, y: 35 },
      { position: 'DMF', x: 38, y: 52 },
      { position: 'DMF', x: 58, y: 52 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '4-2-2-2': {
    name: '4-2-2-2',
    coords: [
      { position: 'CF', x: 39, y: 10 },
      { position: 'CF', x: 57, y: 10 },
      { position: 'LMF', x: 28, y: 38 },
      { position: 'RMF', x: 68, y: 38 },
      { position: 'DMF', x: 39, y: 54 },
      { position: 'DMF', x: 57, y: 54 },
      { position: 'LB', x: 32, y: 71 },
      { position: 'CB', x: 42, y: 71 },
      { position: 'CB', x: 54.5, y: 71 },
      { position: 'RB', x: 68.5, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
  '3-2-4-1': {
    name: '3-2-4-1',
    coords: [
      { position: 'CF', x: 48.5, y: 8 },
      { position: 'LMF', x: 26, y: 33 },
      { position: 'AMF', x: 41, y: 30 },
      { position: 'AMF', x: 56, y: 30 },
      { position: 'RMF', x: 70, y: 33 },
      { position: 'DMF', x: 40, y: 52 },
      { position: 'DMF', x: 57, y: 52 },
      { position: 'CB', x: 33, y: 72 },
      { position: 'CB', x: 48.5, y: 72 },
      { position: 'CB', x: 64, y: 72 },
      { position: 'GK', x: 49.5, y: 88 },
    ],
  },
};
